In [1]:
import seaborn as sns
import pandas as pd

## Coleta de dados

In [2]:
df = sns.load_dataset('mpg')
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

In [3]:
df.to_csv('../data/raw/mpg.csv', index=False)

## Dicionário de dados

In [4]:
dicionario = pd.DataFrame([
    {
        'variavel':'mpg',
        'descricao':'consumo do veículo em milhas por galão (mpg)',
        'tipo':'quantitativa',
        'subtipo':'continua'
    },
    
    {
        'variavel':'cylinders',
        'descricao':'quantidade de cilindros do motor',
        'tipo':'quantitativa',
        'subtipo':'discreta'
    },
    
    {
        'variavel':'displacement',
        'descricao':'cilindrada, capacidade em litros do motor',
        'tipo':'quantitativa',
        'subtipo':'continua'
    },
    
    {
        'variavel':'horsepower',
        'descricao':'potência gerada pelo motor em horsepower (hp)',
        'tipo':'quantitativa',
        'subtipo':'continua'
    },
    
    {
        'variavel':'weight',
        'descricao':'peso total do veículo',
        'tipo':'quantitativa',
        'subtipo':'discreta'
    },
    
    {
        'variavel':'acceleration',
        'descricao':'aceleração',
        'tipo':'quantitativa',
        'subtipo':'continua'
    },
    
    {
        'variavel':'model_year',
        'descricao':'ano de fabricação do veículo de forma abreviada (19XX)',
        'tipo':'quantitativa',
        'subtipo':'discreta'
    },
    
    {
        'variavel':'origin',
        'descricao':'sigla do país onde o veículo foi fabricado',
        'tipo':'qualitativa',
        'subtipo':'nominal'
    },
    
    {
        'variavel':'name',
        'descricao':'nome do veículo',
        'tipo':'qualitativa',
        'subtipo':'nominal'
    }
])

dicionario.to_csv('../data/external/dictionary.csv', index=False)
dicionario

,variavel,descricao,tipo,subtipo
0,mpg,consumo do veículo em milhas por galão (mpg),quantitativa,continua
1,cylinders,quantidade de cilindros do motor,quantitativa,discreta
2,displacement,"cilindrada, capacidade em litros do motor",quantitativa,continua
3,horsepower,potência gerada pelo motor em horsepower (hp),quantitativa,continua
4,weight,peso total do veículo,quantitativa,discreta
5,acceleration,aceleração,quantitativa,continua
6,model_year,ano de fabricação do veículo de forma abreviad...,quantitativa,discreta
7,origin,sigla do país onde o veículo foi fabricado,qualitativa,nominal
8,name,nome do veículo,qualitativa,nominal